### ISSUE TITLE
Using Meteor

### ISSUE THREAD

**Issue by aadamsx** [sokolovstas/SublimeWebInspector#76]
I'm using Meteor which defaults to port 3000.  I can't seem to get web inspector to work with it.

I installed web inspector on osx.  I closed Chrome.  I pressed the shift+command+r key-combo and it states open chrome on port 9222.  I do that and a new chrome window opens.  I got to localhost:3000.  I then go back and press shift+command+r key-combo and it asks me if I want to open chrome on port 9222 again.  It keeps doing this over and over.

In default settings, if I change the port to 3000, nothing happens when press the pressed the shift+command+r key-combo either.  No window opens, no debugging occurs, etc.

**Comment by danmosemsft** [comment]
I don't have Meteor, but as I understand it, it serves the page to localhost:3000. If so that port should not be relevant in any way. The port 9222 is the port that the browser serves up for diagnostics.

Couple thoughts
1) Make sure Chrome is closed before you do "open chrome on 9222". If it's already open, it will ignore the port.
2) After doing "open chrome on 9222" open another browser and navigate to "localhost:9222/json". You should see some JSON. If so the port is open. If not, do "Ctrl-`" in Sublime to see the command line, like:
Running C:\Program Files (x86)\Google\Chrome\Application\chrome.exe --remote-debugging-port=9222 --profile-directory=other2 http://localhost 
Do this from a console window. Does it work then? If not, it's not a web inspector problem, it's something else.
3) If none of that works, add "debug_mode": "true" into your plugin settings, reopen sublime, repeat the process and share the output of the sublime console.

**Comment by danmosemsft** [comment]
As this is so old and it's quite likely one of the above causes is the issue, I'm going to close this. Please reactivate with details if there's still a problem.
